(ns js.lib.r3-drei
  (:require [std.lang :as l]
            [std.lib :as h]))

(l/script :js
  {:macro-only true
   :bundle  {:default [["@react-three/drei" :as ReactThreeDrei]]}})

(h/template-entries [l/tmpl-entry {:type :fragment
                                   :base "ReactThreeDrei"
                                   :tag "js"}]
  [AccumulativeShadows
   AdaptiveDpr
   AdaptiveEvents
   ArcballControls
   AsciiRenderer
   BBAnchor
   Backdrop
   BakeShadows
   Billboard
   Bounds
   Box
   Bvh
   CameraControls
   CameraShake
   Capsule
   CatmullRomLine
   Caustics
   Center
   Circle
   Clone
   Cloud
   ComputedAttribute
   Cone
   ContactShadows
   CubeCamera
   CubicBezierLine
   CurveModifier
   CycleRaycast
   Cylinder
   Decal
   Detailed
   DeviceOrientationControls
   Dodecahedron
   Edges
   Effects
   Environment
   EnvironmentCube
   EnvironmentMap
   EnvironmentPortal
   Example
   Extrude
   FaceControls
   FaceLandmarker
   FaceLandmarkerDefaults
   Facemesh
   FacemeshDatas
   FacemeshEye
   FacemeshEyeDefaults
   FirstPersonControls
   Float
   FlyControls
   GizmoHelper
   GizmoViewcube
   GizmoViewport
   Gltf
   GradientTexture
   Grid
   Html
   Hud
   Icosahedron
   Image
   Instance
   Instances
   IsObject
   KeyboardControls
   Lathe
   Lightformer
   Line
   Loader
   MapControls
   MarchingCube
   MarchingCubes
   MarchingPlane
   Mask
   Merged
   MeshDiscardMaterial
   MeshDistortMaterial
   MeshPortalMaterial
   MeshReflectorMaterial
   MeshRefractionMaterial
   MeshTransmissionMaterial
   MeshWobbleMaterial
   Octahedron
   OrbitControls
   OrthographicCamera
   PerformanceMonitor
   PerspectiveCamera
   PivotControls
   Plane
   Point
   PointMaterial
   PointMaterialImpl
   PointerLockControls
   Points
   PointsBuffer
   Polyhedron
   PositionPoint
   PositionalAudio
   Preload
   PresentationControls
   QuadraticBezierLine
   RandomizedLight
   Reflector
   RenderTexture
   Resize
   Ring
   RoundedBox
   Sampler
   ScreenQuad
   ScreenSpace
   Scroll
   ScrollControls
   Segment
   SegmentObject
   Segments
   Select
   Shadow
   Shape
   Sky
   SoftShadows
   Sparkles
   Sphere
   SpotLight
   SpotLightShadow
   SpriteAnimator
   Stage
   Stars
   Stats
   Svg
   Tetrahedron
   Text
   Text3D
   Torus
   TorusKnot
   TrackballControls
   Trail
   TransformControls
   Tube
   View
   Wireframe
   accumulativeContext
   calcPosFromAngles
   calculateScaleFactor
   isWebGL2Available
   meshBounds
   shaderMaterial
   useAnimations
   useAspect
   useBVH
   useBounds
   useBoxProjectedEnv
   useCamera
   useContextBridge
   useCubeCamera
   useCubeTexture
   useCursor
   useDepthBuffer
   useDetectGPU
   useEnvironment
   useFBO
   useFBX
   useFaceControls
   useFaceLandmarker
   useFont
   useGLTF
   useGizmoContext
   useHelper
   useIntersect
   useKTX2
   useKeyboardControls
   useMask
   useMatcapTexture
   useNormalTexture
   usePerformanceMonitor
   useProgress
   useScroll
   useSelect
   useSurfaceSampler
   useTexture
   useTrail
   useTrailTexture
   useVideoTexture])
